---
title: "Grant parser overview"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(reactable)
library(tidyverse)
library(lubridate)


months <- c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December",
            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")


grants <- read_csv("results/combined_results_sorted.csv") |> 
  mutate(deadline_year = as.numeric(str_extract(deadline, "\\d{4}")),
         deadline_month = str_extract(deadline, paste(months, collapse = "|")),
         deadline_month_numeric = month(parse_date_time(deadline_month, "b"))
         ) |> 
  arrange(deadline_month_numeric) |> 
  filter(deadline_year >= 2025)
```

```{r, echo=FALSE}
grants |> 
  select(-deadline_month_numeric) |> 
  relocate(link, .after = last_col()) |>
  reactable(searchable = TRUE,
          filterable = TRUE,
          defaultPageSize = 50,
          striped = TRUE,
  highlight = TRUE,
  bordered = TRUE)
```

